Repository switch247/mini-expense-tracker, pull requests merged in 2024-12, with the labels that each got.

#6 Update README.md
  README.md
Labels: enhancement

#15 update database connection string to use env variables
  README.md
  utils/dbConfig.jsx
Labels: bug, help wanted, invalid

#14 refactor: fix variable naming and improve code readability in dashboa…
  app/(routes)/dashboard/_components/CardInfo.jsx
  app/(routes)/dashboard/_components/SideNav.jsx
  app/(routes)/dashboard/expenses/page.jsx
  app/(routes)/dashboard/page.jsx
Labels: enhancement, help wanted, invalid

#12 add example environment file and update Header component for dashboar…
  .example.env
  components/Header.jsx
  utils/getExpenseAdvice.js
Labels: enhancement, invalid

#11 fix: correct spelling in Hero component title
  components/Hero.jsx
  public/dashboard.png
Labels: enhancement, invalid
